### ISSUE TITLE
Generate metadata json example files

### ISSUE THREAD

**Issue by jonmjoyce** [asascience-open/nextgen-dmac#14]
The schema doesn't matter right now but should have the basic elements like name, time, dimensions, variables - basically what you see in a netcdf file. Also anything important encoded in the filename, and any other metadata elements that you think are important to users. A generic extraction script for netcdf would be nice down the line but for now whatever is easiest to produce those is fine.

These files will be used to prove out some of the other services.

**Comment by rsignell-usgs** [comment]
@jonmjoyce @benjwadams, for capturing metadata, I would recommend checking out [xstac](https://github.com/TomAugspurger/xstac), which can generate STAC metadata from xarray datasets. (@TomAugspurger is one of the lead developers on [Microsoft's Plantetary Computer](https://planetarycomputer.microsoft.com/).

 Here's a [good recent article about STAC](https://medium.com/radiant-earth-insights/cloud-native-geospatial-outreach-2022-recap-and-videos-2a0e80085db7) and Cloud-Native Geospatial.
