### ISSUE TITLE
Create sample forecast aggregation service

### ISSUE THREAD

**Issue by jonmjoyce** [asascience-open/nextgen-dmac#22]
One of the main capabilities that THREDDS provides is the "best forecast" aggregation. We need to investigate a cloud-native method of aggregating data (ideally without opening all the files) in order to produce the same aggregation. 

This investigation should also lead us to understand what required metadata fields we want to capture along with how best to store and format the data.

**Comment by jonmjoyce** [comment]
It seems that we can use Kerchunk to create virtual time-series aggregations. Need to investigate how we might generalize that function to generate kerchunk files as new data comes in. What's an efficient design to do that?

**Comment by mpiannucci** [comment]
I started work on this last week [here](https://gist.github.com/mpiannucci/2e9717e1f0c5732ac2c6947f1ce44495): an example notebook showing kerchunking over one model run of GFS Wave that is server via NOAA NODD on S3. 

This is only for one model run, but its pretty clear where to go from here I think (at least for grib datasets)

1. Keep around the individual zarr jsons and name them with the forecast and valid time. 
2. Gather allllll of the zarr jsons, and throw out files that are named with the same valid time, defaulting to keep the json with the newest forecast time
3. Create consolidated dataset from the resulting json store files.

**Comment by rsignell-usgs** [comment]
@mpiannucci , yes, the most effective/efficient way to to create these virtual consolidated datasets with Kerchunk is to simply create a Python list of filenames to consolidate!  That way you don't need to cull or manage the individual jsons -- just pick the ones you want to consolidate and include them in the list to pass to `MultiZarrToZarr` !  

Also note that if you have a lot of files to aggregate, say, 1000, you can aggregate them first into aggregations of 100, then aggregate those.    Thus creating an opportunity for parallelization and also reducing the amount of computation the next time you add some data to the virtual collection.   Make sense?

**Comment by mpiannucci** [comment]
From @abkfenris: [xarray_fmrc](https://github.com/abkfenris/xarray_fmrc)

**Comment by abkfenris** [comment]
Specifically I'd point to my ideas for a [`xpublish-fmrc`](https://github.com/abkfenris/xarray_fmrc#xpublish-fmrc) for how Xpublish could take forecast collection datatrees and expand them out into the various FMRC views and could support endpoints to query each. 

That depends on work going on in https://github.com/xarray-contrib/xpublish/pull/140 which I can hopefully get back to soon.

**Comment by emfdavid** [comment]
Excited to look at xpublish-fmrc next week.
Architecturally I do value no having to run a service - just putting blobs in GCS/S3 is quite nice, especially with fsspec caching etc.
One point of clarification, I am training ML models with these aggregations so I have not actually create a single best-timeseries object (the blue highlight - lowest diagonal + right most vertical).
![FMRC](https://docs.unidata.ucar.edu/netcdf-java/current/userguide/images/netcdf-java/tutorial/feature_types/fmrc.png)
For my purposes actually having the 18 hour forecast horizon as a separate time series from the 17, 16 .. 2, 1 hour forecast horizon series is really powerful. I want my model to learn the error in the longer range forecasts and I train different models for each hour. These are the diagonals, (yellow highlight) in the FMRC diagram.
It would be pretty straightforward to add a best-fmrc aggregation to #32 but I haven't done it yet as I don't need it for my work.

**Comment by abkfenris** [comment]
@emfdavid What I've done with xarray_fmrc is made it so that only the individual model run datasets are needed to create a datatree. There is a little metadata munging that happens when creating the tree, but it doesn't have to do any work for a specific view (ex best estimate), until you use the `dt.fmrc` accessor methods. 

At that point it selects into the underlying datasets and returns you a dataset.

I just implemented constant offset accessor method, so `dt.fmrc.constant_offset("18h")` will give you a dataset with only the forecast 18 hours out at each model run.

**Comment by mpiannucci** [comment]
We approached this by using cloud messaging and serverless functions to generate and update aggregations using zarr and kerchunk as the messages come in. So every time a new message arrives, the aggregations are transformed into zarr virtual stores with kerchunk, then those virtual stores and aggregated into a single logical zarr store representing the FMRC and Model Runs. See [cloud_aggregator](https://github.com/asascience-open/nextgen-dmac/tree/main/cloud_aggregator) for an end to end example of the system

**Comment by rsignell-usgs** [comment]
@mpiannucci the link above doesn't work -- did the work get folded into the main branch?

**Comment by mpiannucci** [comment]
> @mpiannucci the link above doesn't work -- did the work get folded into the main branch?

Whoops thanks! Now merged into main so the link should be working now
