### ISSUE TITLE
NcML to kerchunk JSON

### ISSUE THREAD

**Issue by rsignell-usgs** [asascience-open/nextgen-dmac#24]
We have many examples of DMAC model output where datasets are not only aggregated via NcML, but additional metadata is supplied (or corrrected!) to make the virtual datasets delivered by THREDDS more CF-Compliant, UGRID or SGRID compliant, etc. 

It would be great to have a small tool that allows you to copy selected global and variable attribute metadata between two xarray datasets, and save modified metadata into the kerchunk JSON.  

That way you could open an OPeNDAP endpoint backed by a NcML aggregation and update the kerchunk JSON to have the same attributes.  

Here's a use case using IOOS model data:   The USGS COAWST model served on THREDDS has the SGRID conventions, while the kerchunked version does not:

``` python
import xarray as xr
import intake

# Ncml/THREDDS: 
url1 = 'http://geoport.usgs.esipfed.org/thredds/dodsC/coawst_4/use/fmrc/coawst_4_use_best.ncd'
ds1 = xr.open_dataset(url1)       

# Kerchunk/referenceFileSystem
url2 = 'https://mghp.osn.xsede.org/rsignellbucket1/catalogs/ioos_intake_catalog.yml'
cat = intake.open_catalog(url2)
coawst = cat['COAWST-Archive']
ds2 = coawst.to_dask()                 
```

**Comment by rsignell-usgs** [comment]
@mpiannucci thinking this could be a nice win for IOOS -- pretty straightforward small lift, useful to stakeholders, but also to the broader community!

**Comment by mpiannucci** [comment]
I like this idea for sure!

**Comment by rsignell-usgs** [comment]
I've found out about a few things here: 
* [xncml](https://xncml.readthedocs.io/en/latest/tutorial.html#Write-Dataset-back-to-an-ncml-file)
* This [nc_attribute.py](akbfenris) gist from @abkfenris

So one option would be to use xncml to modify attributes, and then just write a tool that writes the global and variable attribute data from NcML to Kerchunk json.
