### ISSUE TITLE
Add metadata publishing capabilities to xpublish

### ISSUE THREAD

**Issue by jonmjoyce** [asascience-open/nextgen-dmac#31]
There should be existing code in [zarrDAP](https://github.com/NCEI-NOAAGov/zarrdap) to create Intake catalogs.

We should also investigate if we can produce STAC items in xpublish.

**Comment by abkfenris** [comment]
I've been thinking some of how to make STAC items in Xpublish in conjunction with https://github.com/xarray-contrib/xpublish/pull/140

With the plugin system, I think we could add a `get_plugins()` dependency. That could return all the plugins that are loaded. Then plugins could have optional methods that return links and assets for a given dataset.

A STAC plugin could then ask all the other plugins what dataset links and assets they have to contribute to an item.
