### ISSUE TITLE
Prototype site is down: https://nextgen-dev.ioos.us/xreds/

### ISSUE THREAD

**Issue by mwengren** [asascience-open/nextgen-dmac#43]
@mpiannucci @jonmjoyce Any ideas what's going on?   

I was looking for the link for a writeup and I noticed the site was down (not sure the link is listed in the repo here, but if not, it should be - once working again of course).

I found it by looking in the slide deck from the June DMAC tech webinar: https://groups.google.com/u/1/g/ioos_tech/c/tVoamUiRAGo/m/k5-2ujgaAQAJ

**Comment by mpiannucci** [comment]
It's back up, thanks for letting us know. 

Some kinks to work out with the memory for the system still :)

**Comment by mpiannucci** [comment]
Im going to close this, let me know if you want it to remain open

**Comment by mwengren** [comment]
Spot check just now, site looks to be down again, FYI.

**Comment by mpiannucci** [comment]
Yeah it's probably a memory/cache balancing act we need to figure out. It's fixed easily by a respawn of the pod

**Comment by jonmjoyce** [comment]
I rebooted the pod yesterday and the site looks like it's up. We've done almost no testing or other software engineering practices as this has been lean prototype development to demonstrate the concept and receive feedback. These are the types of scenarios I'm thinking of when considering what we need to make this a real system. We need monitoring, testing, deployment processes, etc. especially before you start growing the number of datasets and users and the complexity becomes greater.
